name: Build Compiler image
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - run: |
            pushd compiler
              make docker.builder
              make build_in_container
              make docker
            popd