name: Build Compiler image
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Build Compiler image
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GCPServiceAccountKey }}
          GCR_REPOSITORY: gcr.io/nsx-sm
        run: |
            set -x
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | docker login -u _json_key --password-stdin $GCR_REPOSITORY
            git config --global url."https://github.com/".insteadOf "git@github.com:"
            pushd compiler
              make docker.builder
              make build_in_container
              make docker
              make publish
            popd
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - name: Test Generate Code and Render templates
        run: |
            git config --global url."https://github.com/".insteadOf "git@github.com:"
            pushd compiler
              make docker.builder
              make test_in_container
              make test_render_templates
              make test_generate_code_in_container
            popd

